#!/bin/sh

[ -z "$PASSWORD_STORE_DIR" ] && \
    notify-send -i "$XDG_CONFIG_HOME/dunst/critical.png" \
    "Error" "Variable PASSWORD_STORE_DIR not set." && \
    exit 0

for i in dmenu fd pass; do
        ! command -v $i > /dev/null && \
            notify-send -i "$XDG_CONFIG_HOME/dunst/critical.png" \
            "Error" "executable \`$i\` not found." && \
            exit 127
done

entry="$(fd . "$PASSWORD_STORE_DIR" | grep '.*.gpg$' | \
    sed 's/.*password-store\///' | \
    dmenu -i -c -l 15 -p "Choose entry:")"

[ -z $entry ] && exit 1
pass_entry=$(echo $entry | sed -e 's/.gpg$//')
is_card=$(echo $entry | grep -c "credit-card")
is_otp=$(echo $entry | grep -c "otp")

if [ $is_card -ne 0 ]; then
        field="$(printf "Card number\nValid until\nCVV\n" | \
            dmenu -p "Copy which field?" -l 3)"

        case $field in
        "Card number")
                content="$(pass show "$pass_entry" | sed -n '1p')"
                ;;
        "Valid until")
                content="$(pass show "$pass_entry" | sed -n '2p')"
                ;;
        "CVV")
                content="$(pass show "$pass_entry" | sed -n '3p')"
                ;;
        *)
                exit 0
                ;;
        esac

elif [ $is_otp -ne 0 ]; then
	field="$(printf "One-time password\nOTP link\n" | \
	    dmenu -p "Copy which field?" -l 2)"

	case $field in
	"One-time password")
		content="$(pass otp show "$pass_entry")"
		;;
	"OTP link")
		content="$(pass show "$pass_entry")"
		;;
	*)
		exit 0
		;;
	esac

else
        field="$(printf "Password\nUsername\n" | \
            dmenu -p "Copy which field?" -l 2)"

        case $field in
        "Password" )
                content="$(pass show "$pass_entry" | sed -n '1p')"
                ;;
        "Username" )
                content="$(pass show "$pass_entry" | sed -n '2p')"
                ;;
        *)
                exit 0
                ;;
        esac
fi

echo -n "$content" | xclip -selection clipboard
